<?php

namespace Tests\Repositories;

use AlanGiacomin\LaravelBasePack\Repositories\Repository;

class RepositoryTestable extends Repository
{
    public function default(bool $allowNull = true): ?static
    {
        return parent::default($allowNull); // TODO: Change the autogenerated stub
    }
}
