<?php

namespace Alangiacomin\LaravelBasePack\Tests\Events;

use Alangiacomin\LaravelBasePack\Bus\Bus;
use Alangiacomin\LaravelBasePack\Events\EventHandler;
use Alangiacomin\LaravelBasePack\Facades\LaravelBasePackFacade;
use Alangiacomin\LaravelBasePack\Tests\Mocks\Examples\CommandExample;
use Alangiacomin\LaravelBasePack\Tests\Mocks\Examples\EventEmptyHandler;
use Alangiacomin\LaravelBasePack\Tests\Mocks\Examples\EventExample;
use Alangiacomin\LaravelBasePack\Tests\Mocks\Examples\EventExampleHandler;
use Alangiacomin\LaravelBasePack\Tests\Mocks\LaravelBasePackFacadeMock;
use Alangiacomin\LaravelBasePack\Tests\TestCase;

class EventHandlerTests extends TestCase
{
    public EventHandler $handler;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->handler = new EventExampleHandler();
    }

    /**********/
    /* HANDLE */
    /**********/

    public function test_handle()
    {
        new LaravelBasePackFacadeMock();
        LaravelBasePackFacade::shouldReceive('callWithInjection')
            ->once()->withSomeOfArgs('execute');

        $this->handler->handle(new EventExample());
    }

    /****************/
    /* SEND COMMAND */
    /****************/

    public function test_sendCommand()
    {
        $command = new CommandExample();
        LaravelBasePackFacade::shouldReceive('callStaticWithInjection')->with(
            Bus::class,
            'sendCommand',
            ['command' => $command]
        )->once();

        $this->handler->send($command);
    }

    /****************/
    /* SHOULD QUEUE */
    /****************/

    public function test_shouldQueue_true()
    {
        $event = new EventExample();
        $this->handler = new EventExampleHandler();

        $ret = $this->handler->shouldQueue($event);

        expect($ret)->toBeTrue();
    }

    public function test_shouldQueue_false()
    {
        $event = new EventExample();
        $this->handler = new EventEmptyHandler();

        $ret = $this->handler->shouldQueue($event);

        expect($ret)->toBeFalse();
    }
}
