<?php

namespace Alangiacomin\LaravelBasePack\Tests\Console;

use Alangiacomin\LaravelBasePack\Console\Commands\Core\Command;
use Alangiacomin\LaravelBasePack\Tests\TestCase;

class CommandTests extends TestCase
{
    public Command $command;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->command = new CommandTestable();
    }

    /****************/
    /* ELEMENT NAME */
    /****************/

    public function test_elementName_simple()
    {
        // Arrange

        // Act
        $name = $this->command->elementName('SimpleElement');

        // Assert
        expect($name)->toBe('SimpleElement');
    }

    public function test_elementName_complex()
    {
        // Arrange

        // Act
        $name = $this->command->elementName('Complex/Element');

        // Assert
        expect($name)->toBe('Element');
    }

    /*****************************/
    /* NORMALIZE NAMESPACE SLASH */
    /*****************************/

    public function test_normalizeNamespaceSlash_no_slash()
    {
        // Arrange

        // Act
        $name = $this->command->normalizeNamespaceSlash('SimpleElement');

        // Assert
        expect($name)->toBe('SimpleElement');
    }

    public function test_normalizeNamespaceSlash_slash()
    {
        // Arrange

        // Act
        $name = $this->command->normalizeNamespaceSlash('Simple/Element');

        // Assert
        expect($name)->toBe('Simple\Element');
    }

    public function test_normalizeNamespaceSlash_mixed()
    {
        // Arrange

        // Act
        $name = $this->command->normalizeNamespaceSlash('Simple\Mixed/Element');

        // Assert
        expect($name)->toBe('Simple\Mixed\Element');
    }

    /************************/
    /* NORMALIZE PATH SLASH */
    /************************/

    public function test_normalizePathSlash_no_slash()
    {
        // Arrange

        // Act
        $name = $this->command->normalizePathSlash('SimpleElement');

        // Assert
        expect($name)->toBe('SimpleElement');
    }

    public function test_normalizePathSlash_slash()
    {
        // Arrange

        // Act
        $name = $this->command->normalizePathSlash('Simple/Element');

        // Assert
        expect($name)->toBe('Simple/Element');
    }

    public function test_normalizePathSlash_mixed()
    {
        // Arrange

        // Act
        $name = $this->command->normalizePathSlash('Simple\Mixed/Element');

        // Assert
        expect($name)->toBe('Simple/Mixed/Element');
    }

    /************************/
    /* RELATIVE NAMESPACE */
    /************************/

    public function test_relativeNamespace_simple()
    {
        // Arrange

        // Act
        $name = $this->command->relativeNamespace('SimpleElement');

        // Assert
        expect($name)->toBe('');
    }

    public function test_relativeNamespace_sub()
    {
        // Arrange

        // Act
        $name = $this->command->relativeNamespace('Sub/Element');

        // Assert
        expect($name)->toBe('\Sub');
    }

    public function test_relativeNamespace_complex()
    {
        // Arrange

        // Act
        $name = $this->command->relativeNamespace('Complex/Sub/Element');

        // Assert
        expect($name)->toBe('\Complex\Sub');
    }
}
