<?php

namespace Alangiacomin\LaravelBasePack\Tests\Console;

use Alangiacomin\LaravelBasePack\Console\Commands\Core\Command;
use Alangiacomin\LaravelBasePack\Tests\TestCase;

class CommandTests extends TestCase
{
    public Command $command;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->command = new CommandTestable();
    }
}
